/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utente
 */
public class Gioca extends javax.swing.JFrame {

    /**
     * Creates new form Gioca
     */
    public Gioca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CmbSquadra = new javax.swing.JComboBox();
        G1 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        G6 = new javax.swing.JLabel();
        G7 = new javax.swing.JLabel();
        G8 = new javax.swing.JLabel();
        G9 = new javax.swing.JLabel();
        G10 = new javax.swing.JLabel();
        G11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(null);

        jLabel1.setText("Seleziona Squadra");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 30, 90, 30);

        jPanel1.add(CmbSquadra);
        CmbSquadra.setBounds(160, 30, 80, 30);

        G1.setText("G1");
        jPanel1.add(G1);
        G1.setBounds(170, 90, 40, 14);

        G2.setText("G2");
        jPanel1.add(G2);
        G2.setBounds(50, 130, 20, 20);

        G3.setText("G3");
        jPanel1.add(G3);
        G3.setBounds(130, 130, 13, 14);

        G4.setText("G4");
        jPanel1.add(G4);
        G4.setBounds(210, 120, 13, 30);

        G5.setText("G5");
        jPanel1.add(G5);
        G5.setBounds(300, 120, 13, 20);

        G6.setText("G6");
        jPanel1.add(G6);
        G6.setBounds(80, 170, 13, 20);

        G7.setText("G7");
        jPanel1.add(G7);
        G7.setBounds(160, 170, 13, 20);

        G8.setText("G8");
        jPanel1.add(G8);
        G8.setBounds(270, 160, 13, 30);

        G9.setText("G9");
        jPanel1.add(G9);
        G9.setBounds(110, 210, 13, 14);

        G10.setText("G10");
        jPanel1.add(G10);
        G10.setBounds(210, 210, 20, 14);

        G11.setText("G11");
        jPanel1.add(G11);
        G11.setBounds(150, 250, 19, 14);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gioca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbSquadra;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel G10;
    private javax.swing.JLabel G11;
    private javax.swing.JLabel G2;
    private javax.swing.JLabel G3;
    private javax.swing.JLabel G4;
    private javax.swing.JLabel G5;
    private javax.swing.JLabel G6;
    private javax.swing.JLabel G7;
    private javax.swing.JLabel G8;
    private javax.swing.JLabel G9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
